#include <LiquidCrystal.h>
LiquidCrystal lcd(A0,A1,6,5,4,3);

int led13=13;
int led12=12;
int led11=11;
int led10=10;
int led9=9;
int led8=8;
int led7=7;
int led2=2;
int ledA3=A3;
int ledA2=A2;
int ledA4=A4;
int ledA5=A5;

String text;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
 
  pinMode(led13,OUTPUT);
  pinMode(led12,OUTPUT);
  pinMode(led11,OUTPUT);
  pinMode(led10,OUTPUT);
  pinMode(led9,OUTPUT);
  pinMode(led8,OUTPUT);
  pinMode(led7,OUTPUT);
  pinMode(ledA2,OUTPUT);
  pinMode(ledA3,OUTPUT);
  pinMode(ledA4,OUTPUT);
  pinMode(ledA5,OUTPUT);
  pinMode(led2,OUTPUT);
  digitalWrite(led2,HIGH);
  lcd.begin(16,2);
    lcd.clear();
  lcd.print("TECH-A-THON");
  delay(1000);
  lcd.clear();
  lcd.print("TriCore Blaster");
  delay(1000);
  lcd.clear();
  lcd.print("Rituraj Das");
  delay(1000);
  lcd.clear();
  lcd.print("Amit Soren");
  delay(1000);
  lcd.clear();
  lcd.print("Neelesh Ranjan");
  delay(2000);
  lcd.clear();
  lcd.print("TECH-A-THON");
  
  




}

void loop() {
  // put your main code here, to run repeatedly:
     
  while(Serial.available())
  {
    delay(10); 
    char c = Serial.read();
    text+=c;
    
  }
  if(text.length()>0)
  {
    if(text=="zero")
    {
      digitalWrite(led7,LOW);
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
    }
    if(text=="8")
    {
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      
    }
    if(text=="six")
    {
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
      
    }
    if(text=="9")
    {
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      
    }
    if(text=="7")
    {
        digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,LOW);
      
    }
    if(text=="5"){
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
    }
    if(text=="4")
    {
       digitalWrite(led13,LOW);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
    if(text=="3")
    {
       digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
    if(text=="Tu")
    {
         digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,LOW);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
    if(text=="1")
    {
       digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,LOW);
    }
    if(text=="display numbers")
    {
       digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,LOW);
      delay(1000);
       digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,LOW);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      delay(1000);
      digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      delay(1000);
      digitalWrite(led13,LOW);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      delay(1000);
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
      delay(1000);
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
      delay(1000);
      digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,LOW);
      delay(1000);
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      delay(1000);
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      delay(1000);
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(1000);
      digitalWrite(led13,LOW);
      delay(200);
      digitalWrite(ledA2,LOW);
      delay(100);
      digitalWrite(ledA3,LOW);
      delay(100);
      digitalWrite(led7,LOW);
      delay(100);
      digitalWrite(ledA4,LOW);
      delay(100);
      digitalWrite(ledA5,LOW);
      delay(100);
      digitalWrite(led10,LOW);
      delay(100);
      digitalWrite(led12,LOW);
      delay(100);
      digitalWrite(led11,LOW);
      delay(100);
      digitalWrite(led9,LOW);
      delay(100);
      digitalWrite(led8,LOW);
    }
    if(text=="light on")
    {
        digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
    }
    if(text=="light off")
    {
        digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led9,LOW);
      digitalWrite(led8,LOW);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
    }
    if(text=="display patterns")
    {
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(400);
       digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led9,LOW);
      digitalWrite(led8,LOW);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(300);
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(300);
      digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led9,LOW);
      digitalWrite(led8,LOW);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(300);
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(50);
      digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led9,LOW);
      digitalWrite(led8,LOW);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(50);
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(50);
      digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led9,LOW);
      digitalWrite(led8,LOW);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(50);
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(500);
      digitalWrite(led13,LOW);
      delay(200);
      digitalWrite(ledA2,LOW);
      delay(100);
      digitalWrite(ledA3,LOW);
      delay(100);
      digitalWrite(led7,LOW);
      delay(100);
      digitalWrite(ledA4,LOW);
      delay(100);
      digitalWrite(ledA5,LOW);
      delay(100);
      digitalWrite(led10,LOW);
      delay(100);
      digitalWrite(led12,LOW);
      delay(100);
      digitalWrite(led11,LOW);
      delay(100);
      digitalWrite(led9,LOW);
      delay(100);
      digitalWrite(led8,LOW);
      delay(50);
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(50);
      digitalWrite(led13,LOW);
      delay(200);
      digitalWrite(ledA2,LOW);
      delay(100);
      digitalWrite(ledA3,LOW);
      delay(100);
      digitalWrite(led7,LOW);
      delay(100);
      digitalWrite(ledA4,LOW);
      delay(100);
      digitalWrite(ledA5,LOW);
      delay(100);
      digitalWrite(led10,LOW);
      delay(100);
      digitalWrite(led12,LOW);
      delay(100);
      digitalWrite(led11,LOW);
      delay(100);
      digitalWrite(led9,LOW);
      delay(100);
      digitalWrite(led8,LOW);
      delay(200);
       digitalWrite(led13,HIGH);
       delay(100);
      digitalWrite(led12,HIGH);
      delay(100);
      digitalWrite(led10,HIGH);
      delay(100);
      digitalWrite(led11,HIGH);
      delay(100);
      digitalWrite(led9,HIGH);
      delay(100);
      digitalWrite(led8,HIGH);
      delay(100);
      digitalWrite(led13,LOW);
      delay(100);
      digitalWrite(led12,LOW);
      delay(100);
      digitalWrite(led10,LOW);
      delay(100);
      digitalWrite(led11,LOW);
      delay(100);
      digitalWrite(led9,LOW);
      delay(100);
      digitalWrite(led8,LOW);
      delay(100);
       digitalWrite(led13,HIGH);
       delay(100);
      digitalWrite(led12,HIGH);
      delay(100);
      digitalWrite(led10,HIGH);
      delay(100);
      digitalWrite(led11,HIGH);
      delay(100);
      digitalWrite(led9,HIGH);
      delay(100);
      digitalWrite(led8,HIGH);
      delay(100);
      digitalWrite(led13,LOW);
      delay(100);
      digitalWrite(led12,LOW);
      delay(100);
      digitalWrite(led10,LOW);
      delay(100);
      digitalWrite(led11,LOW);
      delay(100);
      digitalWrite(led9,LOW);
      delay(100);
      digitalWrite(led8,LOW);
      delay(100);
        digitalWrite(led13,HIGH);
       delay(100);
      digitalWrite(led12,HIGH);
      delay(100);
      digitalWrite(led10,HIGH);
      delay(100);
      digitalWrite(led11,HIGH);
      delay(100);
      digitalWrite(led9,HIGH);
      delay(100);
      digitalWrite(led8,HIGH);
      delay(100);
      digitalWrite(led13,LOW);
      delay(100);
      digitalWrite(led12,LOW);
      delay(100);
      digitalWrite(led10,LOW);
      delay(100);
      digitalWrite(led11,LOW);
      delay(100);
      digitalWrite(led9,LOW);
      delay(100);
      digitalWrite(led8,LOW);
      delay(100);
        digitalWrite(led13,HIGH);
       delay(100);
      digitalWrite(led12,HIGH);
      delay(100);
      digitalWrite(led10,HIGH);
      delay(100);
      digitalWrite(led11,HIGH);
      delay(100);
      digitalWrite(led9,HIGH);
      delay(100);
      digitalWrite(led8,HIGH);
        delay(100);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
      digitalWrite(led13,LOW);
      delay(100);
      digitalWrite(led12,LOW);
      delay(100);
      digitalWrite(led10,LOW);
      delay(100);
      digitalWrite(led11,LOW);
      delay(100);
      digitalWrite(led9,LOW);
      delay(100);
      digitalWrite(led8,LOW);
      delay(100);
        digitalWrite(led13,HIGH);
       delay(100);
      digitalWrite(led12,HIGH);
      delay(100);
      digitalWrite(led10,HIGH);
      delay(100);
      digitalWrite(led11,HIGH);
      delay(100);
      digitalWrite(led9,HIGH);
      delay(100);
      digitalWrite(led8,HIGH);
      delay(100);
      digitalWrite(led13,LOW);
      delay(100);
      digitalWrite(led12,LOW);
      delay(100);
      digitalWrite(led10,LOW);
      delay(100);
      digitalWrite(led11,LOW);
      delay(100);
      digitalWrite(led9,LOW);
      delay(100);
      digitalWrite(led8,LOW);
        delay(100);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
        digitalWrite(led13,HIGH);
       delay(100);
      digitalWrite(led12,HIGH);
      delay(100);
      digitalWrite(led10,HIGH);
      delay(100);
      digitalWrite(led11,HIGH);
      delay(100);
      digitalWrite(led9,HIGH);
      delay(100);
      digitalWrite(led8,HIGH);
      delay(100);
      digitalWrite(led13,LOW);
      delay(100);
      digitalWrite(led12,LOW);
      delay(100);
      digitalWrite(led10,LOW);
      delay(100);
      digitalWrite(led11,LOW);
      delay(100);
      digitalWrite(led9,LOW);
      delay(100);
      digitalWrite(led8,LOW);
      delay(100);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
       digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
       digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
       digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
       digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
       digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
       digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
    }
    if(text=="oneplus one")
    {
        digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,LOW);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }

        if(text=="oneplus 2")
    {
      digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
      if(text=="2+1")
    {
    digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
         if(text=="oneplus 3")
    {
       digitalWrite(led13,LOW);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
          if(text=="3+1")
    {
       digitalWrite(led13,LOW);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }

         if(text=="oneplus 4")
    {
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
    }

         if(text=="4+1")
    {
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
    }

           if(text=="oneplus 5")
    {
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
    }
          if(text=="5+1")
    {
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
    }

             if(text=="oneplus 6")
    {
      digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,LOW);
    }
             if(text=="6+1")
    {
      digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,LOW);
    }

      if(text=="oneplus 7")
    {
        digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
       if(text=="7+1")
    {
        digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }

      if(text=="oneplus 8")
    {
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
       if(text=="8+1")
    {
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }

     if(text=="2 + 1")
    {
       digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,LOW);
    }
   
    if(text=="2 + 3")
    {
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
      if(text=="3 + 2")
    {
         digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
    }
    if(text=="2 + 2")
    {
      digitalWrite(led13,LOW);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
     if(text=="2 + 5")
    {
        digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,LOW);
    }
       if(text=="5 + 2")
    {
        digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,LOW);
    }
     if(text=="2 + 4")
    {
     digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
    }
      if(text=="4 + 2")
    {
     digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
    }
     if(text=="2 + 6")
    {
     digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }

       if(text=="6 + 2")
    {
     digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
     if(text=="2 + 7")
    {
     digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,LOW); 
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }

      if(text=="7 + 2")
    {
     digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,LOW); 
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
     if(text=="3 + 4")
    {
        digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,LOW);
    }

      if(text=="4 + 3")
    {
        digitalWrite(led13,HIGH);
      digitalWrite(led12,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,LOW);
    }
     if(text=="3 + 5")
    {
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }

       if(text=="5 + 3")
    {
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
     if(text=="3 + 6")
    {
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }

       if(text=="6 + 3")
    {
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }

         if(text=="3 + 3")
    {
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
    }
         if(text=="4 + 4")
    {
        digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
     if(text=="4 + 5")
    {
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }
       if(text=="5 + 4")
    {
      digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,LOW);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
    }

           if(text=="5 + 1")
    {
        digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,LOW);
      digitalWrite(led7,HIGH);
    }

    if(text=="on and off")
    {
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
        digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led9,LOW);
      digitalWrite(led8,LOW);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
        digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led9,LOW);
      digitalWrite(led8,LOW);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
        digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led9,LOW);
      digitalWrite(led8,LOW);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
        digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led9,LOW);
      digitalWrite(led8,LOW);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
        digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led9,LOW);
      digitalWrite(led8,LOW);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
       digitalWrite(led13,HIGH);
      digitalWrite(led12,HIGH);
      digitalWrite(led10,HIGH);
      digitalWrite(led11,HIGH);
      digitalWrite(led9,HIGH);
      digitalWrite(led8,HIGH);
      digitalWrite(led7,HIGH);
      digitalWrite(ledA2,HIGH);
      digitalWrite(ledA3,HIGH);
      digitalWrite(ledA4,HIGH);
      digitalWrite(ledA5,HIGH);
      delay(100);
        digitalWrite(led13,LOW);
      digitalWrite(led12,LOW);
      digitalWrite(led10,LOW);
      digitalWrite(led11,LOW);
      digitalWrite(led9,LOW);
      digitalWrite(led8,LOW);
      digitalWrite(led7,LOW);
      digitalWrite(ledA2,LOW);
      digitalWrite(ledA3,LOW);
      digitalWrite(ledA4,LOW);
      digitalWrite(ledA5,LOW);
      delay(100);
    }
    
      text="";
  }


}
 

 
